name: Add Open Graph Tags
on:
  push:
    branches:
      - main
    paths:
      - "*.html"
  workflow_dispatch:

jobs:
  add-open-graph-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Add Open Graph Tags to HTML files
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const directory = '.'; 
          
          // Wyrażenie regularne do wyszukiwania linków do plików .jpg w tagach <meta>
          const metaTagPattern = /<meta[^>]*content=['\"]([^'\"]+\.jpg)['\"][^>]*>/i;
          
          let changesMade = false;  // Flaga oznaczająca, czy dokonano zmian
          
          if (fs.existsSync(directory)) {
            const files = fs.readdirSync(directory);
            files.forEach(file => {
              const filePath = path.join(directory, file);
              if (file.endsWith('.html') && file !== 'index.html') {
                let content = fs.readFileSync(filePath, 'utf8');
                
                // Przeszukaj tylko tagi <meta> w pliku HTML
                const metaTags = content.match(/<meta[^>]*>/g);
                
                if (metaTags) {
                  let imageLink = null;

                  // Sprawdź każdy tag <meta> pod kątem linku do obrazu .jpg
                  metaTags.forEach(tag => {
                    const match = tag.match(metaTagPattern);
                    if (match && match[1]) {
                      imageLink = match[1];  // Znaleziono link do obrazu
                    }
                  });

                  if (imageLink) {
                    const ogTag = \`<meta property="og:image" content="\${imageLink}">\`;
                    // Dodaj tag og:image, jeśli nie ma go w pliku
                    if (!content.includes('og:image')) {
                      content = content.replace(/<\/head>/, ogTag + '</head>');
                      fs.writeFileSync(filePath, content, 'utf8');
                      console.log('Added Open Graph tag to: ' + filePath);
                      changesMade = true;
                    } else {
                      console.log('Open Graph tag already exists in: ' + filePath);
                    }
                  } else {
                    console.log('No .jpg image found in meta tags of ' + filePath);
                  }
                } else {
                  console.log('No meta tags found in: ' + filePath);
                }
              }
            });

            // Log końcowy
            if (changesMade) {
              console.log('Open Graph tags were successfully added.');
            } else {
              console.log('No changes were made. No Open Graph tags were added.');
            }
          } else {
            console.error('Directory not found: ' + directory);
            process.exit(1);
          }
          "
        shell: /usr/bin/bash -e {0}
