name: Add Open Graph Tags
on:
  push:
    branches:
      - main
    paths:
      - "*.html"
  workflow_dispatch:

jobs:
  add-open-graph-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Add Open Graph Tags to HTML files
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const directory = '.'; 
          
          // Wyrażenie regularne do wyszukiwania linków do plików .jpg w tagach og:image i twitter:image
          const ogTagPattern = /<meta[^>]*property=[\"']og:image[\"'][^>]*content=[\"']([^\"]+\.jpg)[\"'][^>]*>/;
          const twitterTagPattern = /<meta[^>]*name=[\"']twitter:image[\"'][^>]*content=[\"']([^\"]+\.jpg)[\"'][^>]*>/;
          
          let changesMade = false;  // Flaga oznaczająca, czy dokonano zmian
          
          if (fs.existsSync(directory)) {
            const files = fs.readdirSync(directory);
            files.forEach(file => {
              const filePath = path.join(directory, file);
              if (file.endsWith('.html') && file !== 'index.html') {
                let content = fs.readFileSync(filePath, 'utf8');
                
                // Wyszukaj istniejący link w tagu og:image lub twitter:image
                let ogImageMatch = content.match(ogTagPattern);
                let twitterImageMatch = content.match(twitterTagPattern);

                // Wybierz link do obrazu, jeśli istnieje
                let imageLink = ogImageMatch ? ogImageMatch[1] : (twitterImageMatch ? twitterImageMatch[1] : null);

                if (imageLink) {
                  const ogTag = \`<meta property="og:image" content="\${imageLink}">\`;
                  if (!content.includes('og:image')) { 
                    content = content.replace('</head>', ogTag + '</head>');
                    fs.writeFileSync(filePath, content, 'utf8');
                    console.log('Added Open Graph tag to: ' + filePath);
                    // Zmienna changesMade na true, ponieważ dokonano zmiany
                    changesMade = true;
                  }
                } else {
                  console.log('No image link found in ' + filePath);
                }
              }
            });
          } else {
            console.error('Directory not found: ' + directory);
            process.exit(1);
          }

          // Na koniec dodajemy log, który informuje o zakończeniu operacji
          if (changesMade) {
            console.log('Open Graph tags were successfully added.');
          } else {
            console.log('No changes were made. No Open Graph tags were added.');
          }
          "
        shell: /usr/bin/bash -e {0}
