name: Add Open Graph Tags

on:
  push:
    branches:
      - main
    paths:
      - "*.html"
  workflow_dispatch:

jobs:
  add-open-graph-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Add Open Graph Tags to HTML files
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const directory = '.'; 
          
          // Wyrażenie regularne do wyszukiwania linków do plików .jpg w tagach og:image i twitter:image
          const metaTagPattern = /<meta[^>]*content=['\"]([^'\"]+\.jpg)['\"][^>]*>/i;
          
          let changesMade = false;  // Flaga oznaczająca, czy dokonano zmian
          
          if (fs.existsSync(directory)) {
            const files = fs.readdirSync(directory);
            files.forEach(file => {
              const filePath = path.join(directory, file);
              if (file.endsWith('.html') && file !== 'index.html') {
                console.log('Processing file: ' + filePath);
                
                // Odczytaj plik HTML
                let content = fs.readFileSync(filePath, 'utf8');
                
                // Ogranicz przetwarzanie tylko do pierwszych 25 linii
                const first25Lines = content.split('\n').slice(0, 25).join('\n');

                // Znajdź wszystkie tagi meta w pierwszych 25 liniach
                const metaTags = first25Lines.match(/<meta[^>]*>/g);
                if (metaTags) {
                  console.log('Found meta tags in first 25 lines:', metaTags);
                  let imageLink = null;

                  // Sprawdź każdy tag meta
                  metaTags.forEach(tag => {
                    const match = tag.match(metaTagPattern);
                    if (match && match[1]) {
                      imageLink = match[1];
                      console.log('Found image link:', imageLink);
                    }
                  });

                  if (imageLink) {
                    const ogTag = \`<meta property="og:image" content="\${imageLink}">\`;
                    if (!content.includes('og:image')) {
                      content = content.replace(/<\/head>/, ogTag + '</head>');
                      fs.writeFileSync(filePath, content, 'utf8');
                      console.log('Added Open Graph tag to: ' + filePath);
                      changesMade = true;
                    } else {
                      console.log('Open Graph tag already exists in: ' + filePath);
                    }
                  } else {
                    console.log('No .jpg image found in meta tags of ' + filePath);
                  }
                } else {
                  console.log('No meta tags found in the first 25 lines of: ' + filePath);
                }
              }
            });
          } else {
            console.error('Directory not found: ' + directory);
            process.exit(1);
          }

          // Na koniec dodajemy log, który informuje o zakończeniu operacji
          if (changesMade) {
            console.log('Open Graph tags were successfully added.');
          } else {
            console.log('No changes were made. No Open Graph tags were added.');
          }
          "
        shell: /usr/bin/bash -e {0}
