name: Add Open Graph Tags
on:
  push:
    branches:
      - main
    paths:
      - "*.html"
  workflow_dispatch:

jobs:
  add-open-graph-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Add Open Graph Tags to HTML files
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const directory = '.';
          const ogTag = '<meta property=\"og:image\" content=\"https://example.com/thumbnail.jpg\">';
          if (fs.existsSync(directory)) {
            const files = fs.readdirSync(directory);
            files.forEach(file => {
              const filePath = path.join(directory, file);
              if (file.endsWith('.html') && file !== 'index.html') {
                let content = fs.readFileSync(filePath, 'utf8');
                if (!content.includes('og:image')) { 
                  content = content.replace('</head>', ogTag + '</head>');
                  fs.writeFileSync(filePath, content, 'utf8');
                  console.log('Added Open Graph tags to: ' + filePath);
                }
              }
            });
          } else {
            console.error('Directory not found: ' + directory);
            process.exit(1);
          }
          "
