name: Rename Files
on:
  push:
    paths:
      - "html/*.html"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  rename-files:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Rename HTML files
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const problematicChars = /[^\w.-]/g;
          const directory = './html';
          if (fs.existsSync(directory)) {
            fs.readdirSync(directory).forEach(file => {
              const filePath = path.join(directory, file);
              console.log(`Processing file: ${file}`);
              if (file.endsWith('.html') && problematicChars.test(file)) {
                const newName = file.replace(problematicChars, '-');
                fs.renameSync(filePath, path.join(directory, newName));
                console.log(`Renamed: ${file} -> ${newName}`);
              }
            });
          } else {
            console.error(`Directory not found: ${directory}`);
            process.exit(1);
          }
          "

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Rename problematic HTML files" || echo "No changes to commit"

      - name: Push changes
        run: git push
