name: Rename Files
on:
  push:
    branches:
      - main
    paths:
      - "html/*.html"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  rename-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Ensure html directory exists
        run: |
          if [ ! -d "./html" ]; then
            echo "Directory not found: ./html"
            exit 1
          fi

      - name: Rename problematic files
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const problematicChars = /[^\w.-]/g;
          const directory = './html';
          fs.readdirSync(directory).forEach(file => {
            const filePath = path.join(directory, file);
            console.log('Processing file: ' + file);
            if (file.endsWith('.html') && problematicChars.test(file)) {
              const newName = file.replace(problematicChars, '-');
              fs.renameSync(filePath, path.join(directory, newName));
              console.log('Renamed: ' + file + ' -> ' + newName);
            }
          });
          "

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Rename problematic HTML files" || echo "No changes to commit"

      - name: Push changes
        run: git push
