name: Rename Files
on:
  push:
    branches:
      - main
    paths:
      - "html/*.html"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  rename-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create html directory if it does not exist
        run: mkdir -p ./html

      - name: Rename problematic files
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const problematicChars = /[^a-zA-Z0-9]/g;
          const directory = './html';
          const removePolishChars = (str) => {
            const polishChars = {
              'ą': 'a', 'ć': 'c', 'ę': 'e', 'ł': 'l', 'ń': 'n', 'ó': 'o', 'ś': 's', 'ź': 'z', 'ż': 'z',
              'Ą': 'A', 'Ć': 'C', 'Ę': 'E', 'Ł': 'L', 'Ń': 'N', 'Ó': 'O', 'Ś': 'S', 'Ź': 'Z', 'Ż': 'Z'
            };
            return str.replace(/[ąćęłńóśźżĄĆĘŁŃÓŚŹŻ]/g, char => polishChars[char] || char);
          };
          if (fs.existsSync(directory)) {
            fs.readdirSync(directory).forEach(file => {
              const filePath = path.join(directory, file);
              console.log('Processing file: ' + file);
              if (file.endsWith('.html')) {
                let newName = removePolishChars(file).replace(problematicChars, '');
                console.log('New name: ' + newName);
                fs.renameSync(filePath, path.join(directory, newName));
                console.log('Renamed: ' + file + ' -> ' + newName);
              }
            });
          } else {
            console.error('Directory not found: ' + directory);
            process.exit(1);
          }
          "

      - name: Check Git status
        run: git status

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Rename problematic HTML files" || echo "No changes to commit"

      - name: Push changes
        run: git push
