name: Rename Files and Add Open Graph Tags
on:
  push:
    branches:
      - main
    paths:
      - "*.html"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  process-html-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: List files in root directory before processing
        run: ls -la

      - name: Rename problematic files
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const problematicChars = /[^a-zA-Z0-9]/g;
          const directory = '.';
          const removePolishChars = (str) => {
            const polishChars = {
              'ą': 'a', 'ć': 'c', 'ę': 'e', 'ł': 'l', 'ń': 'n', 'ó': 'o', 'ś': 's', 'ź': 'z', 'ż': 'z',
              'Ą': 'A', 'Ć': 'C', 'Ę': 'E', 'Ł': 'L', 'Ń': 'N', 'Ó': 'O', 'Ś': 'S', 'Ź': 'Z', 'Ż': 'Z'
            };
            return str.replace(/[ąćęłńóśźżĄĆĘŁŃÓŚŹŻ]/g, char => polishChars[char] || char);
          };
          if (fs.existsSync(directory)) {
            const files = fs.readdirSync(directory);
            files.forEach(file => {
              const filePath = path.join(directory, file);
              if (file.endsWith('.html') && file !== 'index.html') {
                let newName = removePolishChars(file).replace(problematicChars, '');
                newName = newName.replace(/html+$/, ''); // Usuń wszystkie wystąpienia "html" na końcu
                newName += '.html'; // Dodaj jedno "html" na końcu
                fs.renameSync(filePath, path.join(directory, newName));
              }
            });
          } else {
            console.error('Directory not found: ' + directory);
            process.exit(1);
          }
          "

      - name: Add Open Graph Tags to HTML files
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const directory = '.';

          // Funkcja dodająca Open Graph Tags
          const addOpenGraphTags = (htmlContent, fileName) => {
            const ogTitle = 'Generated File: ' + fileName;
            const ogDescription = 'This is a description for ' + fileName;
            const ogImage = 'https://example.com/path-to-image.jpg'; // Podmień na odpowiednią ścieżkę
            const ogUrl = 'https://example.com/' + fileName;

            const ogTags = \`
<meta property='og:title' content='\${ogTitle}' />
<meta property='og:description' content='\${ogDescription}' />
<meta property='og:image' content='\${ogImage}' />
<meta property='og:url' content='\${ogUrl}' />
\`;

            // Dodaj tagi do sekcji <head>
            if (htmlContent.includes('<head>')) {
              return htmlContent.replace('<head>', \`<head>\${ogTags}\`);
            } else {
              console.error('No <head> tag found in file:', fileName);
              return htmlContent;
            }
          };

          // Przetwarzanie plików HTML
          if (fs.existsSync(directory)) {
            const files = fs.readdirSync(directory);
            files.forEach(file => {
              const filePath = path.join(directory, file);
              if (file.endsWith('.html') && file !== 'index.html') {
                const htmlContent = fs.readFileSync(filePath, 'utf-8');
                const updatedContent = addOpenGraphTags(htmlContent, file);
                fs.writeFileSync(filePath, updatedContent, 'utf-8');
                console.log('Added Open Graph Tags to:', file);
              }
            });
          } else {
            console.error('Directory not found:', directory);
            process.exit(1);
          }
          "

      - name: Check Git status
        run: git status

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Processed HTML files: renamed and added Open Graph Tags" || echo "No changes to commit"

      - name: Push changes
        run: git push
